- src/main/java/net/coru/kloadgen/input/AvroSchemaProcessor.java
- src/main/java/net/coru/kloadgen/input/avro/AvroSubjectPropertyEditor.java
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/util/ProducerKeysHelper.java
> I5 single union support

- pom.xml
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/GenericKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/KafkaSampler.java
- src/main/java/net/coru/kloadgen/util/AvroRandomTool.java
- src/main/java/net/coru/kloadgen/util/RandomTool.java
- src/main/java/net/coru/kloadgen/util/StatelessRandomTool.java
- src/test/java/net/coru/kloadgen/util/AvroRandomToolTest.java
- src/test/java/net/coru/kloadgen/util/RandomToolTest.java
- src/test/java/net/coru/kloadgen/util/StatelessRandomToolTest.java
Adding optionality for headers
> Add variable support

- LICENSE
> Updated license to GPL V3

- src/main/java/net/coru/kloadgen/extractor/SchemaExtractor.java
> #47 Fix Schema Extractor

- src/main/java/net/coru/kloadgen/config/avroserialized/AvroSerializedConfigElementBeanInfo.java
- src/main/java/net/coru/kloadgen/config/schemaregistry/DefaultPropertiesHelper.java
- src/main/java/net/coru/kloadgen/config/schemaregistry/SchemaRegistryConfigElement.java
- src/main/java/net/coru/kloadgen/extractor/SchemaExtractor.java
- src/main/java/net/coru/kloadgen/loadgen/BaseLoadGenerator.java
- src/main/java/net/coru/kloadgen/loadgen/impl/AvroLoadGenerator.java
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/GenericKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/KafkaSampler.java
- src/test/java/net/coru/kloadgen/loadgen/impl/AvroLoadGeneratorTest.java
Adding Request Headers to Sampler
> #45 Adding Request Headers to Sampler

- pom.xml
- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
#54 Fix Optional array generation issue
> #54 Fix Optional array generation issue

- README.md
- pom.xml
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/GenericKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/KafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
> #58 new sampler properties issue

- .github/workflows/greetings.yml
- Example-Test-Plan.jmx
- Example-Variable-Substitution.jmx
- pom.xml
- src/main/java/net/coru/kloadgen/config/avroserialized/AvroSerializedConfigElementBeanInfo.java
- src/main/java/net/coru/kloadgen/config/schemaregistry/DefaultPropertiesHelper.java
- src/main/java/net/coru/kloadgen/config/schemaregistry/SchemaRegistryConfigElement.java
- src/main/java/net/coru/kloadgen/extractor/SchemaExtractorImpl.java
- src/main/java/net/coru/kloadgen/input/avro/AvroSubjectPropertyEditor.java
- src/main/java/net/coru/kloadgen/input/avro/SchemaRegistryConfigPropertyEditor.java
- src/main/java/net/coru/kloadgen/model/FieldValueMapping.java
- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
- src/main/java/net/coru/kloadgen/util/AvroRandomTool.java
- src/main/java/net/coru/kloadgen/util/RandomTool.java
- src/test/java/net/coru/kloadgen/input/avro/SchemaExtractorTest.java
- src/test/java/net/coru/kloadgen/processor/AvroSchemaProcessorTest.java
- src/test/java/net/coru/kloadgen/testutil/FileHelper.java
- src/test/java/net/coru/kloadgen/util/RandomToolTest.java
- src/test/resources/avro-files/testOptionalMap.avsc
#60 Fix edge condition for subject name loading
> #60 Fix edge condition for subject name loading

- pom.xml
- src/main/java/net/coru/kloadgen/extractor/SchemaExtractorImpl.java
- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
> add array extractor changes

- README.md
- pom.xml
- src/main/java/net/coru/kloadgen/sampler/AbstractKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/ConfluentKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/GenericBinaryKafkaSampler.java
- src/main/java/net/coru/kloadgen/sampler/KafkaSampler.java
- src/main/java/net/coru/kloadgen/serializer/GenericAvroRecordBinarySerializer.java
Hi!
Add support for avro binary serialization.
> fix code duplication, add GenericAvroRecordBinarySerializer and sampler

- Example-Test-Plan.jmx
- pom.xml
- src/main/java/net/coru/kloadgen/config/valuefileserialized/ValueFileSerializedConfigElementBeanInfo.java
- src/main/java/net/coru/kloadgen/model/FieldValueMapping.java
- src/test/java/net/coru/kloadgen/model/FieldValueMappingTest.java
#78 support json schema in value field
> #78 support json schema in value field

- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
> #89 Fix Array Generation

- src/main/java/net/coru/kloadgen/util/RandomTool.java
- src/test/java/net/coru/kloadgen/util/AvroRandomToolTest.java
> #93 Fix Number size generator

- README.md
I've found some minor typos in the README and I thought it could be useful to suggest a change :D
> Some minor typos

- pom.xml
Upgrading lombok version to fix this issue:
https://github.com/projectlombok/lombok/issues/2790
> upgrading lombok version

- src/main/java/net/coru/kloadgen/extractor/extractors/AvroExtractor.java
- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
- src/main/java/net/coru/kloadgen/randomtool/random/RandomObject.java
> Fix enum values bad generation

- Example-Test-Plan-2.jmx
- pom.xml
- src/main/java/net/coru/kloadgen/sampler/KafkaSchemaSampler.java
- src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
- src/main/java/net/coru/kloadgen/util/SchemaRegistryKeyHelper.java
Fix #145 enabling autoregister
> #145 enabling autoregister

- pom-github.xml
- pom.xml
- src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
- src/main/java/net/coru/kloadgen/processor/SchemaProcessorLib.java
- src/test/java/net/coru/kloadgen/processor/AvroSchemaProcessorTest.java
- src/test/resources/avro-files/avros-example-with-sub-entity-array-test.avsc
Also increase pom.version as suggested here: https://github.com/t-h-e/kloadgen/commit/84f41c7aeb06ec85599a0edea447009912fa3fa5#commitcomment-62980242
> Fix record and simple arrays in subentities

- pom-github.xml
- pom.xml
- src/main/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorTool.java
- src/test/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorToolTest.java
> Improve sequential generation support

- .github/workflows/greetings.yml
Texts shown when action is triggered have been updated.
> Texts updated in greetings.yml

- pom-github.xml
- pom.xml
- src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
Fixes a error on Consumer configuration to make it capable of connecting to a Schema Registry using authentication.
> #172 not able add components to plan

- .gitignore
- pom-maven-central.xml
- pom.xml
- src/main/java/net/coru/kloadgen/processor/ProtoBufProcessorHelper.java
#204 Fix build Object with no native classes.
> #204 Fix build Object with no native classes.

- pom-maven-central.xml
- pom.xml
- src/main/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorTool.java
- src/test/java/net/coru/kloadgen/processor/JsonSchemaProcessorTest.java
- src/test/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorToolTest.java
Fix sequence generation when setted as optional
Fixes the problem that occurred when generating a sequence marked as optional in Avro.
> #208 sequence and defaults

- docs/installation.md
Include information regarding installation from Maven Central
> Maven central update

- docs/_Sidebar.md
- docs/about.md
- docs/example-test-plan.md
- docs/getting-started.md
- docs/how-to-run.md
- docs/producer-configuration.md
- docs/release-notes.md
- docs/schemas.md
Minor typos fixed and style changes done in order to have the documentation structure ready for a technical review.
> Minor changes pre final review

- docs/how-to-run.md
> Fixes typo

- docs/release-notes.md
> Update release notes

- docs/additional-information.md
Related to #207, contributing guidelines check
> References to contributing guidelenes removed

- pom-maven-central.xml
Changed pom version fixing error in maven central build
> #318 changed pom version for maven central build

- pom-maven-central.xml
- pom.xml
- src/main/java/com/sngular/kloadgen/processor/util/SchemaProcessorUtils.java
When we create the definition from the schema we were passing a null object instead of the correct element. We solved this getting the correct object and passing it to the required method
> Fixed getting wrong element from nested types

- .github/workflows/maven-central-push.yml
- .github/workflows/maven-pr-review.yml
> #379 Enable batch mode in deployment

- docs/postman/kloadgen.postman_collection.json
Resolves #401 by adding a basic postman collection to documentation
> :hammer: Added basic Postman collection to import
